apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: bca-idx-btc-run-${STARTBLOCKHEIGHT}
  namespace: ${NAMESPACE}
spec:
  taskRef:
    name: bca-idx-btc
  podTemplate:
    securityContext:
      fsGroup: 65532
      runAsUser: 1000
    taskPodTemplate:
      nodeSelector:
        kubernetes.io/arch: amd64
  serviceAccountName: sa-bca
  computeResources:
        requests:
          cpu: "900m"
          memory: "999Mi"
        limits:
          cpu: "1500m"
          memory: "1999Mi"    
  workspaces:
  - name: minio-credentials
    secret:
      secretName: minio-credentials
  - name: rpc-credentials
    secret:
      secretName: rpc-credentials
  - name: ca-cert
    secret:
      secretName: ca-cert
  params:
  - name: start-blockheight
    value: ${STARTBLOCKHEIGHT}
  - name: num-blocks
    value: ${NUMBLOCKS}
